# target_name
mode: phase0_v1_2

#model
model_name: vae_v1
pretrain_file: ./result/Phase0_vae_v1_1_b64_lr1e-3_6.pt
model_file: ./result/Phase0_vae_linear_origin_b64_lr1e-3_6.pt

#data
dataset_name: ARCDataset
train_data: ./data/phase0_train_v1_2.json
valid_data: ./data/phase0_valid_v1_2.json
test_data: None

#hyperparameters
seed: 777
lr: 5e-5
epochs: 200
train_batch_size: 32
valid_batch_size: 1
kind_of_loss: mse
optimizer: Lion
scheduler: LambdaLR
lr_lambda: 0.97
step_size: 10
gamma: 0.5

#options
use_permute: True
use_rotate: True
use_pretrain: True
use_train: True
use_valid: True
use_test: False
use_wandb: False
use_batch: True
use_size: True

#etc
save_dir: './result'
trainer: Phase0_v1_2_Trainer
cuda_num: 0