# target_name
mode: phase1-concept-multi-bc-v2

#model
model_name: vae_classifier_v2
pretrain_file: None
model_file: ./result/Phase0_vae_linear_origin_b64_lr1e-3_6.pt


#data
dataset_name: New_ARCDataset
train_data: ./data/phase1_concept_train_fusion_layer_v2.json
valid_data: ./data/phase1_concept_valid_fusion_layer_v2.json
test_data: None

#hyperparameters
seed: 777
lr: 5e-5
epochs: 200
train_batch_size: 32
valid_batch_size: 1
kind_of_loss: bce
optimizer: AdamW
scheduler: LambdaLR
lr_lambda: 0.97
step_size: 10
gamma: 0.5

#options
use_permute: True
use_rotate: False
use_pretrain: False
use_train: True
use_valid: True
use_test: False
use_wandb: False
use_batch: True
use_size: True

#etc
save_dir: './result'
trainer: Phase1_Trainer
cuda_num: 0